[google]
GOOGLE_API_KEY = "AIzaSyB3IKC-kLBl5u2vuHpD60MT-ipJ-ug3lLs"
GOOGLE_CLIENT_ID = "739626899325-s5gmp45st6tfnpvtghn7kv7u67did1j3.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

[oauth]
client_id = "739626899325-s5gmp45st6tfnpvtghn7kv7u67did1j3.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://your-app-name.streamlit.app/callback/google"
